### ISSUE TITLE
Moving from Sass-Lint to Stylelint

### ISSUE THREAD

**Issue by evyperez** [oficiodesign/initial-css#1]
We need to switching Sass Lint to stylelint because Sass Lint is no longer being maintained.

**Comment by Eduruiz** [comment]
My last stylelintrc.yml is far from what we get with sass-lint, but it's a start
```
---
plugins:
- stylelint-selector-bem-pattern

extends:
- stylelint-config-sass-guidelines
- stylelint-config-rational-order

rules:
  no-duplicate-selectors: true
  declaration-block-no-duplicate-properties: true
  order/properties-alphabetical-order:
  selector-class-pattern:
  - "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$"
  - message: Class names should match the hyphenated BEM naming convention
  ```
