### ISSUE TITLE
Update print style

### ISSUE THREAD

**Issue by robsonsobral** [oficiodesign/initial-css#33]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/33) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

We should add:

```scss
  * {
    box-shadow: none !important;
  }

 article p {
    max-width: none;
  }

  .site-footer,
  .no-print {
    display: none;
  }
```

[Good source](https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/)
