### ISSUE TITLE
Printing only first page

### ISSUE THREAD

**Issue by robsonsobral** [oficiodesign/initial-css#38]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/38) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

Sticky footer rules crash the print styles. So:

```css
  html,
  body {
    display: block;

    height: auto;
    max-height: none;
  }
```
