### ISSUE TITLE
Hide drop arrow on input[list] in Chrome

### ISSUE THREAD

**Issue by robsonsobral** [oficiodesign/initial-css#60]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/60) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

```scss
// hide drop arrow on input[list] in Chrome
[list]::-webkit-calendar-picker-indicator {
  opacity: 0;
}
```

‌
