### ISSUE TITLE
Add focus mixin

### ISSUE THREAD

**Issue by robsonsobral** [oficiodesign/initial-css#90]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/90) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

```scss
@mixin focused {
  outline: 0;

  box-shadow: 0 0 0 4px rgba(palette('accent'), 0.5);
}
```

‌
